check_mate/urls.py
from django.urls import path

from . import views

app_name = "check_mate"

urlpatterns=[
    path("", views.index, name='index'),
    # ex. /login
    path("login", views.login_user, name="login"),
    # ex. /logout
    path("logout", views.user_logout, name="logout"),
    # ex. /register
    path("register", views.register, name="register"),
    # ex. /projects
    path("projects", views.projects, name="projects"),
    # ex. /projects/filter
    path("projects/filter", views.projects_filter, name="projects_filter"),
    # ex. /projects/5
    path("projects/<int:project_id>", views.project_details, name="project_details"),
    # ex. /projects/5/filter
    path("projects/<int:project_id>/filter", views.project_detail_filter, name="project_detail_filter"),
    # ex. /projects/add
    path("projects/add", views.project_add, name="project_add"),
    # ex. /projects/5/delete
    path("projects/<int:project_id>/delete", views.project_delete, name="project_delete"),
    # ex. /projects/5/edit
    path("projects/<int:project_id>/edit", views.project_edit, name="project_edit"),
    # ex. /ticket/1
    path("ticket/<int:ticket_id>", views.ticket_detail, name="ticket_details"),
    # ex. /ticket/1/filter
    path("ticket/<int:ticket_id>/filter", views.ticket_filter_tags, name="ticket_filter_tags"),
    # ex. /ticket/1/history
    path("ticket/<int:ticket_id>/history", views.ticket_detail, name="ticket_history"),
    # ex. /ticket/add
    path("ticket/add", views.ticket_add, name="ticket_add"),
    # ex. /ticket/1/delete
    path("ticket/<int:ticket_id>/delete", views.ticket_delete, name="ticket_delete"),
    # ex. /ticket/1/edit
    path("ticket/<int:ticket_id>/edit", views.ticket_edit, name="ticket_edit"),
    # ex. /task/add
    path("task/add", views.task_add, name="task_add"),
    # ex. /task/1/edit
    path("task/<int:task_id>/edit", views.task_edit, name="task_edit"),
    # ex. /task/1/delete
    path("task/<int:task_id>/delete", views.task_delete, name="task_delete"),
    # ex. /stand-up
    path("stand-up", views.stand_up_view, name="stand-up"),
    # ex. /stand-up/filter
    path("stand-up/filter", views.filter_stand_up, name="filter_stand_up"),
    # ex /stand-up/claim
    path("stand-up/claim", views.claim_tickets_tasks, name="claim"),
    # ex /stand-up/claim/edit
    path("claim/edit", views.remove_claim, name="remove-claim"),
    # ex /stand-up/claim/view-all
    path("stand-up/claim/view-all", views.claim_tickets_tasks, name="claim-all"),
]

project/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls import include, url

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('check_mate.urls'))
]

check_mate/views/auth_views.py
from django.contrib.auth import logout, login, authenticate
from django.contrib.auth.decorators import login_required
from django.http import HttpResponse, HttpResponseRedirect, Http404
from django.shortcuts import render
from django.template import RequestContext
from django.urls import reverse
from django.contrib import messages

from check_mate.forms import UserForm, LogInForm

# TODO: Style home page


def register(request):
    '''Handles the creation of a new user for authentication

    Method arguments:
      request -- The full HTTP request object
    '''

    # A boolean value for telling the template whether the registration was successful.
    # Set to False initially. Code changes value to True when registration succeeds.
    registered = False

    # Create a new user by invoking the `create_user` helper method
    # on Django's built-in User model
    if request.method == 'POST':
        user_form = UserForm(data=request.POST)

        if user_form.is_valid():
            # Save the user's form data to the database.
            user = user_form.save()

            # Now we hash the password with the set_password method.
            # Once hashed, we can update the user object.
            user.set_password(user.password)
            user.save()

            # Update our variable to tell the template registration was successful.
            registered = True

            return login_user(request)

    elif request.method == 'GET':
        user_form = UserForm()
        template_name = 'register.html'
        context = {'user_form': user_form, 'next': request.GET.get('next', '/')}
        return render(request, template_name, context)

# which would capture the next pass to registration form
# Upon submit grab the next value in the form on the post that will be passed down to login

def login_user(request):
    '''Handles the creation of a new user for authentication

    Method arguments:
      request -- The full HTTP request object
    '''

    # Obtain the context for the user's request.
    context = {'next': request.GET.get('next', '/'), "login_form": LogInForm()}

    # If the request is a HTTP POST, try to pull out the relevant information.
    if request.method == 'POST':
        # Use the built-in authenticate method to verify
        username=request.POST['username']
        password=request.POST['password']
        authenticated_user = authenticate(username=username, password=password)

        # If authentication was successful, log the user in
        if authenticated_user is not None:
            login(request=request, user=authenticated_user)
            if request.POST.get('next') == '/':
                return HttpResponseRedirect('/')
            else:
                return HttpResponseRedirect(request.POST.get('next', '/'))

        else:
            # Bad login details were provided. So we can't log the user in.
            messages.error(request, "Login failed. Your username or password is incorrect.")

    return render(request, 'login.html', context)

# Use the login_required() decorator to ensure only those logged in can access the view.
@login_required
def user_logout(request):
    # Since we know the user is logged in, we can now just log them out.
    logout(request)

    # Take the user back to the homepage. Is there a way to not hard code
    # in the URL in redirects?????
    return HttpResponseRedirect('/')

check_mate/views/index.py
from django.shortcuts import render

def index(request):
    context = {}
    template_name = 'index.html'
    return render(request, template_name, context)

check_mate/views/project_views.py
import datetime

from django.shortcuts import render
from django.http import HttpResponseRedirect
from django.contrib.auth.decorators import login_required
from django.urls import reverse
from django.contrib import messages
from django.db.models import Q

from check_mate.models import *
from check_mate.forms import ProjectForm

# Non-MVP Notes--------------------------------------------
# V2: Make sure every project has a status in fixtures
# ----------------------------------------------------------



@login_required
def projects(request):
    """This view collects all projects and renders them using the projects.html template

    Returns:
        [render] -- returns the projects.html template with all projects passed in
    """

    projects = Project.objects.all()
    context = {
        "projects": projects
    }
    return render(request, 'projects.html', context)

@login_required
def projects_filter(request):

    if request.method == "POST":
        status = []

        for item in request.POST:
            if "status" in item:
                if "_" in item.split("-")[1]:
                    new_item = item.split("-")[1]
                    status.append(" ".join(new_item.split("_")))
                else:
                    status.append(item.split("-")[1])

        projects = Project.objects.filter(project_status__in=status)

        context = {
            "projects": projects,
            "selected_status": status
        }

    return render(request, 'projects.html', context)

@login_required
def project_details(request, project_id):
    """This function loads a specific project's detail page

    Arguments:
        project_id {int} -- the id of the specific project details being requested

    Returns:
        [render] -- returns the project_details.html template with specific project details and all associated tickets passed in
    """
    user_list = []

    project_detail = Project.objects.get(pk=project_id)
    tickets = Ticket.objects.filter(project=project_id)
    ticket_tags = Ticket.objects.filter(project=project_id)
    tasks = Task.objects.filter(ticket__in=tickets)

    for ticket in tickets:
        if ticket.ticket_assigned_user is not None:
            if ticket.ticket_assigned_user not in user_list:
                user_list.append(ticket.ticket_assigned_user)

    for task in tasks:
        if task.task_assigned_user is not None:
            if task.task_assigned_user not in user_list:
                user_list.append(task.task_assigned_user)

    context = {
        "project_detail": project_detail,
        "tickets": tickets,
        "ticket_tags": ticket_tags,
        "user_list": user_list
    }
    return render(request, "project_details.html", context)

@login_required
def project_detail_filter(request, project_id):

    if request.method == "POST":
        project_detail = Project.objects.get(pk=project_id)
        ticket_tags = Ticket.objects.filter(project=project_id)
        tasks = Task.objects.filter(ticket__in=ticket_tags)
        tag_list = []
        users = []
        user_list = []

        for ticket in ticket_tags:
            if ticket.ticket_assigned_user is not None:
                if ticket.ticket_assigned_user not in user_list:
                    user_list.append(ticket.ticket_assigned_user)

        for task in tasks:
            if task.task_assigned_user is not None:
                if task.task_assigned_user not in user_list:
                    user_list.append(task.task_assigned_user)

        for item in request.POST:
            if "tag" in item:
                tag_list.append(item.split("-")[1])
            if "user" in item:
                users.append(item.split("-")[1])

        if user_list and tag_list:
            selected_tags = Tag.objects.filter(pk__in=tag_list)
            selected_users = User.objects.filter(pk__in=users)
            tickets = Ticket.objects.filter(project=project_id).filter(Q(tags__in=selected_tags)| Q(ticket_assigned_user__in=selected_users)).distinct()
        elif tag_list:
            selected_tags = Tag.objects.filter(pk__in=tag_list)
            tickets = Ticket.objects.filter(project=project_id).filter(tags__in=selected_tags).distinct()
            selected_users = []
        elif user_list:
            selected_users = User.objects.filter(pk__in=users)
            tickets = Ticket.objects.filter(project=project_id).filter(ticket_assigned_user__in=selected_users).distinct()
            selected_tags = []

        context={
            "project_detail": project_detail,
            "tickets": tickets,
            "ticket_tags": ticket_tags,
            "selected_tags": selected_tags,
            "selected_users": selected_users,
            "user_list": user_list
        }

    return render(request, "project_details.html", context)


@login_required
def project_add(request):
    """Handles the addition of new projects from the main project board

    Returns:
        [render] -- if the request is a GET, or there is an error with the form data, will return a render of project_add.html with an error message (when applicable)
        [HttpResponseRedirect] -- when the request to POST a new project is successful, it will redirect to the main projects view with the new project added
    """
    project_form = ProjectForm()
    form_data = request.POST

    if request.method == "POST":
        completed_project_form = ProjectForm(form_data)

        if completed_project_form.is_valid():
            project_name = form_data["project_name"]
            project_description = form_data["project_description"]
            project_due = form_data["project_due"]

            if project_name == "" or project_description == "":
                context = {
                    "project_form": completed_project_form
                }

                messages.error(request, "You must complete all fields in the form")

            else:
                new_project = Project(project_name=project_name, project_description= project_description, project_due=project_due, project_created=datetime.date.today(),project_status = "Not Started")
                new_project.save()

                messages.success(request, "Project successfully saved")

                return HttpResponseRedirect(reverse("check_mate:projects"))

    else:
        context = {
            "project_form": project_form
        }
    return render(request, "project_form.html", context)


@login_required
def project_delete(request, project_id):
    """Handles checking if a project can be deleted and the deletion of appropriate projects. Projects can only be deleted if they do not have any tickets associated with them.

    Arguments:
        project_id {int} -- the id of the project we would like to delete

    Returns:
        [render] -- if the request is a GET, will return a render of project_delete.html with permissions to delete a project
        [HttpResponseRedirect] -- when the POST request to remove a project is successful, it will redirect to the main projects view with the requested project removed
    """

    if request.method == "POST":
        project= Project.objects.get(pk=project_id)
        project.delete()
        messages.success(request, "Project successfully deleted")
        return HttpResponseRedirect(reverse("check_mate:projects"))
    else:
        project = Project.objects.get(pk=project_id)

        context = {
            "project": project,
        }
        return render(request, "project_delete.html", context)


@login_required
def project_edit(request, project_id):
    """Handles rendering a pre-populated edit form with existing project data and update of project details

    Arguments:
        project_id {int} -- The id of the project we would like to edit

    Returns:
        [render] -- if the request is a GET, will return a render of project_edit.html with pre-populated information in project form
        [HttpResponseRedirect] -- when the POST request to update a project is successful, it will redirect to the project detail view with the project details updated
    """
    project = Project.objects.get(pk=project_id)
    form_data = request.POST

    if request.method == "GET":
        project_form = ProjectForm(instance=project)
        context = {
            "project": project,
            "project_form": project_form
        }

        return render(request, "project_form.html", context)

    elif request.method == "POST":
        project.project_name = form_data["project_name"]
        project.project_description = form_data["project_description"]

        if form_data["project_due"]:
            project.project_due = form_data["project_due"]

        project.save()

        messages.success(request, "Changes successfully saved")

        return HttpResponseRedirect(reverse("check_mate:project_details", args=(project_id, )))

check_mate/templates/home.html
{% extends "index.html" %}

check_mate/templates/index.html
{% load staticfiles %}

<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <meta http-equiv="X-UA-Compatible" content="ie=edge" />
    <title>{% block title %}Check Mate{% endblock title %}</title>
    <link
      rel="stylesheet"
      href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css"
      integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO"
      crossorigin="anonymous"
    />
    <link rel="stylesheet" href="{% static 'main.css' %}"/>
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.7.2/css/all.css" integrity="sha384-fnmOCqbTlWIlj8LyTjo7mOUStjsKC4pOpQbqyi7RrhN7udi9RwhKkMHpvLbHG9Sr" crossorigin="anonymous">
    {% block css %}
    {% endblock css %}
    {% block js_head %}
    {% endblock js_head %}
  </head>
  <body>
    <!-- Nav Bar -->
    <nav class="navbar navbar-expand-md navbar-light bg-info ">
      <a class="navbar-brand text-white" href="#">Check Mate</a>
      <ul class="navbar-nav nav ml-auto">
        {% if user.is_authenticated %}
        <li class="nav-item"><a class="nav-link text-white" href="{% url 'check_mate:projects' %}">Projects</a></li>
        <li class="nav-item"><a class="nav-link text-white" href="{% url 'check_mate:stand-up' %}">Stand Up</a></li>
        <li class="nav-item dropdown">
          <a class="nav-link text-white dropdown-toggle" href="#" id="navbarDropdownMenuLink" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
            Welcome, {{user.first_name}}
          </a>
          <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdownMenuLink">
            <a class="dropdown-item" href="{% url 'check_mate:logout' %}">Log Out</a>
          </div>
        </li>
        {% else %}
        <li class="nav-item"><a class="nav-link text-white" href="{% url 'check_mate:login'%}">Log In</a></li>
        {% endif %}
      </ul>
    </nav>
    <!-- End Nav Bar -->
    <!-- Filter Nav Bar -->
    <div class="bg-light">
      <div class="container">
        {% block navfilter %}
        {% endblock navfilter%}
      </div>
    </div>
    <!-- End Filter Nav Bar -->
    <br />
    <div class="container mt-3">{% block content %} {% endblock content %}</div>
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
    {% block js %}{% endblock js%}
  </body>
</html>

check_mate/templates/project_form.html
{% extends "index.html" %}

{% load crispy_forms_tags %}

{% block content %}

{% for message in messages %}
  {% if message.tags == "error" %}
    <div class="alert-danger alert" role="alert">{{message}}</div>
  {% else %}
    <div class="alert-{{message.tags}} alert" role="alert">{{message}}</div>
  {% endif %}
{% endfor%}

{% if project %}
  <h1>Edit Project</h1>
  <form action="{% url 'check_mate:project_edit' project.id%}" method="POST">
{% else %}
  <h1>Add Projects</h1>
  <form action="{% url 'check_mate:project_add' %}" method="POST">
{% endif %}

    {% csrf_token %}
    {{ project_form|crispy}}

    {% if project %}
      <input class="btn btn-info" type="submit" value="Save Changes"/>
      <a class="btn btn-success" href="{% url 'check_mate:project_details' project.id %}">Go Back</a>
    {% else %}
      <input class="btn btn-info" type="submit" value="Add Project"/>
      <a class="btn btn-success" href="{% url 'check_mate:projects' %}">Go Back</a>
    {% endif %}
  </form>
{% endblock content %}

check_mate/templates/register.html
{% extends 'index.html' %}

{% block content %}
  <h1>Register with Bangazon</h1>

  <!-- Completed Registration Section -->
  {% if registered %}
    <strong>Thank you for registering!</strong>
    <a href="{% url 'check_mate:index' %}">Return to the homepage.</a><br />
  <!-- End Completed Registration Section -->
  <!-- Registration Form Section -->
  {% else %}
    <strong>Register here!</strong><br />
    <form id="user_form" method="post" action="{% url 'check_mate:register' %}" enctype="multipart/form-data">
      {% csrf_token %}
      {{ user_form.as_p }}

      <input type="hidden" value="{{next}}" name="next"/>
      <input class="btn btn-info" type="submit" name="submit" value="Register" />
    </form>
  {% endif %}
  <!-- End Registration Form Section -->
{% endblock content %}

check_mate/templates/stand_up.html
{% extends 'index.html' %}

{% load ticket_card %}
{% load task_card %}

{% comment %}
<!-- V2: put user's name in stand up -->
{% endcomment %}

{% block navfilter %}
<!-- Filtering Section -->
<div class="row ml-3 mt-3">
  <div class="col">
    <p class="collapse-text" data-toggle="collapse" data-target="#collapseExample" aria-expanded="false" aria-controls="collapseExample">Filter Results<i class="ml-3 fas fa-angle-down"></i></p>
  </div>
</div>
<div class="row ml-3 mt-3 collapse" id="collapseExample">
  <div class="col">
    <div class="row">
      <div class="col">
        <form action="{% url 'check_mate:filter_stand_up' %}" method="POST">
          {% csrf_token %}
          <div class="row">
            <div class="col">
              <h6>Projects</h6>
              {% for project in projects %}
                <div class="form-group form-check">
                  {% if project in selected_projects %}
                    <input type="checkbox" checked class="form-check-input" id="project-{{project.id}}" name="project-{{project.id}}">
                  {% else %}
                    <input type="checkbox" class="form-check-input" id="project-{{project.id}}" name="project-{{project.id}}">
                  {% endif %}
                  <label class="form-check-label" for="project-{{project.id}}">{{project.project_name}}</label>
                </div>
              {% endfor %}
            </div>
            <div class="col">
              <h6>Status</h6>
                <div class="form-group form-check">
                  {% if "Not Started" in selected_status %}
                    <input type="checkbox" checked class="form-check-input" id="status-Not_Started" name="status-Not_Started">
                  {% else %}
                    <input type="checkbox" class="form-check-input" id="status-Not_Started" name="status-Not_Started">
                  {% endif %}
                  <label class="form-check-label" for="status-Not_Started">Not Started</label>
                </div>
                <div class="form-group form-check">
                  {% if "Active" in selected_status %}
                    <input type="checkbox" checked class="form-check-input" id="status-Active" name="status-Active">
                  {% else %}
                    <input type="checkbox" class="form-check-input" id="status-Active" name="status-Active">
                  {% endif %}
                  <label class="form-check-label" for="status-Active">Active</label>
                </div>
                <div class="form-group form-check">
                  {% if "Road Block" in selected_status %}
                    <input type="checkbox" checked class="form-check-input" id="status-Road_Block" name="status-Road_Block">
                  {% else %}
                    <input type="checkbox" class="form-check-input" id="status-Road_Block" name="status-Road_Block">
                  {% endif %}
                  <label class="form-check-label" for="status-Road_Block">Road Block</label>
                </div>
                <div class="form-group form-check">
                  {% if "Complete" in selected_status %}
                    <input type="checkbox" checked class="form-check-input" id="status-Complete" name="status-Complete">
                  {% else %}
                    <input type="checkbox" class="form-check-input" id="status-Complete" name="status-Complete">
                  {% endif %}
                  <label class="form-check-label" for="status-Complete">Complete</label>
                </div>
            </div>
          </div>
        </div>
      </div>
      <div class="row">
        <div class="col">
          <button type="submit" class="btn btn-info">Filter</button>
          <a href="{% url 'check_mate:stand-up' %}" class="btn btn-secondary">Clear</a>
        </div>
      </div>
    </form>
  </div>
</div>
<!-- End Filtering Section -->
{% endblock navfilter%}

{% block content %}
  <div class="row">
    <div class="col">
      <h2>Stand Up</h2>
    </div>
    <div class="col text-right">
      {% if claimed_tickets or claimed_tasks %}
      <a class="btn btn-info" href="{% url 'check_mate:remove-claim' %}">Edit claimed tickets</a>
      {% else %}
      <a class="btn btn-info" href="{% url 'check_mate:claim' %}">Claim tickets for today</a>
      {% endif %}
    </div>
  </div>
  <div class="row mt-3 horizontal-container flex-nowrap">
    <div class="col-6">
      <div class="row bg-info pt-3">
        <div class="col text-white flex-column text-center">
          <h6>Yesterday</h6>
        </div>
      </div>
      <div class="row">
        <div class="col border shadow-sm pt-2 ticket-container">
          <h6 class="text-center">New Tickets</h6>
          {% if tickets %}
            {% for ticket in tickets %}
              {% ticket_card ticket.id False False %}
            {% endfor %}
          {% else %}
          <div class="card" style="width:16rem;">
            <div class="card-body">
              <div class="card-title text-dark">No New Tickets Created Yesterday</div>
            </div>
          </div>
          {% endif %}
          <h6 class="text-center pt-2">New Tasks</h6>
          {% if tasks %}
            {% for task in tasks %}
              {% task_card task.id False False %}
            {% endfor %}
          {% else %}
          <div class="card" style="width:16rem;">
            <div class="card-body">
              <div class="card-title text-dark">No New Tasks Created Yesterday</div>
            </div>
          </div>
          {% endif %}
        </div>
        <div class="col border shadow-sm pt-2 ticket-container">
          <h6 class="text-center">Your Activity Yesterday</h6>
          {% if ticket_activity or task_activity %}
            {% for key, value in ticket_activity.items %}
              <div class="card" style="width:16rem;">
                <div class="card-header">
                  <div class="card-title text-dark">{{key}}</div>
                </div>
                <div class="card-body">
                  {% for ticket in value %}
                    <p class="mb-0 ticket-description">{{ticket.get_ticket_history_description}}</p>
                    <p class="ticket-description text-muted">{{ticket.activity_date | date:"l, F d, Y"}}</p>
                  {% endfor %}
                </div>
              </div>
            {% endfor %}
            {% for key, value in task_activity.items %}
            <div class="card" style="width:16rem;">
              <div class="card-header">
                <div class="card-title text-dark">{{key}}</div>
              </div>
              <div class="card-body">
                {% for task in value %}
                  <p class="mb-0 ticket-description">{{task.get_task_history_description}}</p>
                  <p class="ticket-description text-muted">{{task.activity_date | date:"l, F d, Y"}}</p>
                {% endfor %}
              </div>
            </div>
            {% endfor %}
          {% endif %}
        </div>
      </div>
    </div>
    <div class="col-3">
      <div class="row bg-info pt-3">
        <div class="col text-white flex-column text-center">
          <h6>Today</h6>
        </div>
      </div>
      <div class="row">
        <div class="col border shadow-sm pt-2 ticket-container">
          {% if claimed_tickets %}
          <h6 class="text-center">Tickets</h6>
            {% for ticket in claimed_tickets %}
              {% ticket_card ticket.ticket_id False False %}
            {% endfor %}
          {% endif %}
          {% if claimed_tasks%}
          <h6 class="text-center pt-2">Tasks</h6>
            {% for task in claimed_tasks %}
              {% task_card task.task_id False False %}
            {% endfor %}
          {% endif %}
        </div>
      </div>
    </div>
    <div class="col-3">
      <div class="row bg-info pt-3">
        <div class="col text-white flex-column text-center">
          <h6>Road Blocks</h6>
        </div>
      </div>
      <div class="row">
        <div class="col border shadow-sm pt-2 ticket-container">
          {% if road_blocked_tickets %}
            {% for ticket in road_blocked_tickets %}
              {% ticket_card ticket.id False False %}
            {% endfor %}
          {% endif %}
          {% if road_blocked_tasks %}
            {% for task in road_blocked_tasks %}
              {% task_card task.id False False %}
            {% endfor %}
          {% endif %}
        </div>
      </div>
    </div>
  </div>
{% endblock content %}

{% block js%}
<script>
  $(function () {
    $('[data-toggle="tooltip"]').tooltip()
  })
</script>
{% endblock js %}

check_mate/templates/task_form.html
{% extends "index.html" %}

{% load crispy_forms_tags %}

{% block css %}
  {{task_form.media.css}}
{% endblock css%}

{% block content %}

{% for message in messages %}
  {% if message.tags == "error" %}
    <div class="alert-danger alert" role="alert">{{message}}</div>
  {% else %}
    <div class="alert-{{message.tags}} alert" role="alert">{{message}}</div>
  {% endif %}
{% endfor%}

{% if task %}
  <h1>Edit Task</h1>
  <form action="{% url 'check_mate:task_edit' task.id %}" method="POST">
{% else %}
  <h1>Add Task</h1>
  <form action="{% url 'check_mate:task_add' %}" method="POST">
    <input type="hidden" value="{{ticket}}" name="ticket"/>
{% endif %}

    {% csrf_token %}
    {{task_form|crispy}}

    {% if task_status %}
      {{task_status|crispy}}
    {% endif %}

    <input class="btn btn-info" type="submit" value="Save Task"/>
    <a class="btn btn-success" href="{% url 'check_mate:ticket_details' ticket %}">Go Back</a>
  </form>
{% endblock content %}

{% block js %}
  {{task_form.media.js}}
{% endblock js %}

check_mate/templates/ticket_form.html
{% extends "index.html" %}

{% load crispy_forms_tags %}

{% block css %}
  {{ticket_form.media.css}}
{% endblock css %}

{% block content %}

{% for message in messages %}
  {% if message.tags == "error" %}
    <div class="alert-danger alert" role="alert">{{message}}</div>
  {% else %}
    <div class="alert-{{message.tags}} alert" role="alert">{{message}}</div>
  {% endif %}
{% endfor%}

{% if ticket %}
  <h1>Edit Ticket</h1>
  <form action="{% url 'check_mate:ticket_edit' ticket.id %}" method="POST">
{% else %}
  <h1>Add Ticket</h1>
  <form action="{% url 'check_mate:ticket_add' %}" method="POST">
    <input type="hidden" value="{{project}}" name="project"/>
{% endif %}

    {% csrf_token %}
    {{ticket_form|crispy}}

    {% if ticket_status %}
      {{ticket_status|crispy}}
    {% endif %}

    <input class="btn btn-info" type="submit" value="Save Ticket"/>
    {% if ticket %}
      <a class="btn btn-success" href="{% url 'check_mate:ticket_details' ticket.id %}">Go Back</a>
    {% else %}
      <a class="btn btn-success" href="{% url 'check_mate:project_details' project %}">Go Back</a>
    {% endif %}
  </form>
{% endblock content %}

{% block js %}
  {{ticket_form.media.js}}
{% endblock js%}