check_mate/urls.py
from django.urls import path

from . import views

app_name = "check_mate"

urlpatterns=[
    path("", views.index, name='index'),
    # ex. /login
    path("login", views.login_user, name="login"),
    # ex. /logout
    path("logout", views.user_logout, name="logout"),
    # ex. /register
    path("register", views.register, name="register"),
    # ex. /projects
    path("projects", views.projects, name="projects"),
    # ex. /projects/filter
    path("projects/filter", views.projects_filter, name="projects_filter"),
    # ex. /projects/5
    path("projects/<int:project_id>", views.project_details, name="project_details"),
    # ex. /projects/5/filter
    path("projects/<int:project_id>/filter", views.project_detail_filter, name="project_detail_filter"),
    # ex. /projects/add
    path("projects/add", views.project_add, name="project_add"),
    # ex. /projects/5/delete
    path("projects/<int:project_id>/delete", views.project_delete, name="project_delete"),
    # ex. /projects/5/edit
    path("projects/<int:project_id>/edit", views.project_edit, name="project_edit"),
    # ex. /ticket/1
    path("ticket/<int:ticket_id>", views.ticket_detail, name="ticket_details"),
    # ex. /ticket/1/filter
    path("ticket/<int:ticket_id>/filter", views.ticket_filter_tags, name="ticket_filter_tags"),
    # ex. /ticket/1/history
    path("ticket/<int:ticket_id>/history", views.ticket_detail, name="ticket_history"),
    # ex. /ticket/add
    path("ticket/add", views.ticket_add, name="ticket_add"),
    # ex. /ticket/1/delete
    path("ticket/<int:ticket_id>/delete", views.ticket_delete, name="ticket_delete"),
    # ex. /ticket/1/edit
    path("ticket/<int:ticket_id>/edit", views.ticket_edit, name="ticket_edit"),
    # ex. /task/add
    path("task/add", views.task_add, name="task_add"),
    # ex. /task/1/edit
    path("task/<int:task_id>/edit", views.task_edit, name="task_edit"),
    # ex. /task/1/delete
    path("task/<int:task_id>/delete", views.task_delete, name="task_delete"),
    # ex. /stand-up
    path("stand-up", views.stand_up_view, name="stand-up"),
    # ex. /stand-up/filter
    path("stand-up/filter", views.filter_stand_up, name="filter_stand_up"),
    # ex /stand-up/claim
    path("stand-up/claim", views.claim_tickets_tasks, name="claim"),
    # ex /stand-up/claim/edit
    path("claim/edit", views.remove_claim, name="remove-claim"),
    # ex /stand-up/claim/view-all
    path("stand-up/claim/view-all", views.claim_tickets_tasks, name="claim-all"),
]

project/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls import include, url

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('check_mate.urls'))
]

check_mate/views/auth_views.py
from django.contrib.auth import logout, login, authenticate
from django.contrib.auth.decorators import login_required
from django.http import HttpResponse, HttpResponseRedirect, Http404
from django.shortcuts import render
from django.template import RequestContext
from django.urls import reverse
from django.contrib import messages

from check_mate.forms import UserForm, LogInForm

# TODO: Style home page


def register(request):
    '''Handles the creation of a new user for authentication

    Method arguments:
      request -- The full HTTP request object
    '''

    # A boolean value for telling the template whether the registration was successful.
    # Set to False initially. Code changes value to True when registration succeeds.
    registered = False

    # Create a new user by invoking the `create_user` helper method
    # on Django's built-in User model
    if request.method == 'POST':
        user_form = UserForm(data=request.POST)

        if user_form.is_valid():
            # Save the user's form data to the database.
            user = user_form.save()

            # Now we hash the password with the set_password method.
            # Once hashed, we can update the user object.
            user.set_password(user.password)
            user.save()

            # Update our variable to tell the template registration was successful.
            registered = True

            return login_user(request)

    elif request.method == 'GET':
        user_form = UserForm()
        template_name = 'register.html'
        context = {'user_form': user_form, 'next': request.GET.get('next', '/')}
        return render(request, template_name, context)

# which would capture the next pass to registration form
# Upon submit grab the next value in the form on the post that will be passed down to login

def login_user(request):
    '''Handles the creation of a new user for authentication

    Method arguments:
      request -- The full HTTP request object
    '''

    # Obtain the context for the user's request.
    context = {'next': request.GET.get('next', '/'), "login_form": LogInForm()}

    # If the request is a HTTP POST, try to pull out the relevant information.
    if request.method == 'POST':
        # Use the built-in authenticate method to verify
        username=request.POST['username']
        password=request.POST['password']
        authenticated_user = authenticate(username=username, password=password)

        # If authentication was successful, log the user in
        if authenticated_user is not None:
            login(request=request, user=authenticated_user)
            if request.POST.get('next') == '/':
                return HttpResponseRedirect('/')
            else:
                return HttpResponseRedirect(request.POST.get('next', '/'))

        else:
            # Bad login details were provided. So we can't log the user in.
            messages.error(request, "Login failed. Your username or password is incorrect.")

    return render(request, 'login.html', context)

# Use the login_required() decorator to ensure only those logged in can access the view.
@login_required
def user_logout(request):
    # Since we know the user is logged in, we can now just log them out.
    logout(request)

    # Take the user back to the homepage. Is there a way to not hard code
    # in the URL in redirects?????
    return HttpResponseRedirect('/')

check_mate/views/index.py
from django.shortcuts import render

def index(request):
    context = {}
    template_name = 'index.html'
    return render(request, template_name, context)

check_mate/views/project_views.py
import datetime

from django.shortcuts import render
from django.http import HttpResponseRedirect
from django.contrib.auth.decorators import login_required
from django.urls import reverse
from django.contrib import messages
from django.db.models import Q

from check_mate.models import *
from check_mate.forms import ProjectForm

# Non-MVP Notes--------------------------------------------
# V2: Make sure every project has a status in fixtures
# ----------------------------------------------------------



@login_required
def projects(request):
    """This view collects all projects and renders them using the projects.html template

    Returns:
        [render] -- returns the projects.html template with all projects passed in
    """

    projects = Project.objects.all()
    context = {
        "projects": projects
    }
    return render(request, 'projects.html', context)

@login_required
def projects_filter(request):

    if request.method == "POST":
        status = []

        for item in request.POST:
            if "status" in item:
                if "_" in item.split("-")[1]:
                    new_item = item.split("-")[1]
                    status.append(" ".join(new_item.split("_")))
                else:
                    status.append(item.split("-")[1])

        projects = Project.objects.filter(project_status__in=status)

        context = {
            "projects": projects,
            "selected_status": status
        }

    return render(request, 'projects.html', context)

@login_required
def project_details(request, project_id):
    """This function loads a specific project's detail page

    Arguments:
        project_id {int} -- the id of the specific project details being requested

    Returns:
        [render] -- returns the project_details.html template with specific project details and all associated tickets passed in
    """
    user_list = []

    project_detail = Project.objects.get(pk=project_id)
    tickets = Ticket.objects.filter(project=project_id)
    ticket_tags = Ticket.objects.filter(project=project_id)
    tasks = Task.objects.filter(ticket__in=tickets)

    for ticket in tickets:
        if ticket.ticket_assigned_user is not None:
            if ticket.ticket_assigned_user not in user_list:
                user_list.append(ticket.ticket_assigned_user)

    for task in tasks:
        if task.task_assigned_user is not None:
            if task.task_assigned_user not in user_list:
                user_list.append(task.task_assigned_user)

    context = {
        "project_detail": project_detail,
        "tickets": tickets,
        "ticket_tags": ticket_tags,
        "user_list": user_list
    }
    return render(request, "project_details.html", context)

@login_required
def project_detail_filter(request, project_id):

    if request.method == "POST":
        project_detail = Project.objects.get(pk=project_id)
        ticket_tags = Ticket.objects.filter(project=project_id)
        tasks = Task.objects.filter(ticket__in=ticket_tags)
        tag_list = []
        users = []
        user_list = []

        for ticket in ticket_tags:
            if ticket.ticket_assigned_user is not None:
                if ticket.ticket_assigned_user not in user_list:
                    user_list.append(ticket.ticket_assigned_user)

        for task in tasks:
            if task.task_assigned_user is not None:
                if task.task_assigned_user not in user_list:
                    user_list.append(task.task_assigned_user)

        for item in request.POST:
            if "tag" in item:
                tag_list.append(item.split("-")[1])
            if "user" in item:
                users.append(item.split("-")[1])

        if user_list and tag_list:
            selected_tags = Tag.objects.filter(pk__in=tag_list)
            selected_users = User.objects.filter(pk__in=users)
            tickets = Ticket.objects.filter(project=project_id).filter(Q(tags__in=selected_tags)| Q(ticket_assigned_user__in=selected_users)).distinct()
        elif tag_list:
            selected_tags = Tag.objects.filter(pk__in=tag_list)
            tickets = Ticket.objects.filter(project=project_id).filter(tags__in=selected_tags).distinct()
            selected_users = []
        elif user_list:
            selected_users = User.objects.filter(pk__in=users)
            tickets = Ticket.objects.filter(project=project_id).filter(ticket_assigned_user__in=selected_users).distinct()
            selected_tags = []

        context={
            "project_detail": project_detail,
            "tickets": tickets,
            "ticket_tags": ticket_tags,
            "selected_tags": selected_tags,
            "selected_users": selected_users,
            "user_list": user_list
        }

    return render(request, "project_details.html", context)


@login_required
def project_add(request):
    """Handles the addition of new projects from the main project board

    Returns:
        [render] -- if the request is a GET, or there is an error with the form data, will return a render of project_add.html with an error message (when applicable)
        [HttpResponseRedirect] -- when the request to POST a new project is successful, it will redirect to the main projects view with the new project added
    """
    project_form = ProjectForm()
    form_data = request.POST

    if request.method == "POST":
        completed_project_form = ProjectForm(form_data)

        if completed_project_form.is_valid():
            project_name = form_data["project_name"]
            project_description = form_data["project_description"]
            project_due = form_data["project_due"]

            if project_name == "" or project_description == "":
                context = {
                    "project_form": completed_project_form
                }

                messages.error(request, "You must complete all fields in the form")

            else:
                new_project = Project(project_name=project_name, project_description= project_description, project_due=project_due, project_created=datetime.date.today(),project_status = "Not Started")
                new_project.save()

                messages.success(request, "Project successfully saved")

                return HttpResponseRedirect(reverse("check_mate:projects"))

    else:
        context = {
            "project_form": project_form
        }
    return render(request, "project_form.html", context)


@login_required
def project_delete(request, project_id):
    """Handles checking if a project can be deleted and the deletion of appropriate projects. Projects can only be deleted if they do not have any tickets associated with them.

    Arguments:
        project_id {int} -- the id of the project we would like to delete

    Returns:
        [render] -- if the request is a GET, will return a render of project_delete.html with permissions to delete a project
        [HttpResponseRedirect] -- when the POST request to remove a project is successful, it will redirect to the main projects view with the requested project removed
    """

    if request.method == "POST":
        project= Project.objects.get(pk=project_id)
        project.delete()
        messages.success(request, "Project successfully deleted")
        return HttpResponseRedirect(reverse("check_mate:projects"))
    else:
        project = Project.objects.get(pk=project_id)

        context = {
            "project": project,
        }
        return render(request, "project_delete.html", context)


@login_required
def project_edit(request, project_id):
    """Handles rendering a pre-populated edit form with existing project data and update of project details

    Arguments:
        project_id {int} -- The id of the project we would like to edit

    Returns:
        [render] -- if the request is a GET, will return a render of project_edit.html with pre-populated information in project form
        [HttpResponseRedirect] -- when the POST request to update a project is successful, it will redirect to the project detail view with the project details updated
    """
    project = Project.objects.get(pk=project_id)
    form_data = request.POST

    if request.method == "GET":
        project_form = ProjectForm(instance=project)
        context = {
            "project": project,
            "project_form": project_form
        }

        return render(request, "project_form.html", context)

    elif request.method == "POST":
        project.project_name = form_data["project_name"]
        project.project_description = form_data["project_description"]

        if form_data["project_due"]:
            project.project_due = form_data["project_due"]

        project.save()

        messages.success(request, "Changes successfully saved")

        return HttpResponseRedirect(reverse("check_mate:project_details", args=(project_id, )))

check_mate/templates/reusable_components/progress_bar.html
<div class="progress">
    <div class="progress-bar bg-success" role="progressbar" style="width: calc({{complete}}/{{total}}*100%)" aria-valuenow="{{complete}}" aria-valuemin="0" aria-valuemax="{{total}}"></div>
    <div class="progress-bar bg-info" role="progressbar" style="width: calc({{active}}/{{total}}*100%)" aria-valuenow="{{active}}" aria-valuemin="0" aria-valuemax="{{total}}"></div>
</div>

check_mate/templates/reusable_components/section_header.html
{% load status_badge %}
{% load progress_bar %}

<div class="row">
  <div class="col">
    <div class="row px-3">
      <div class="col d-flex align-items-center">
        {% if user_initials %}
          <div class="text-white initials-circle bg-info mr-2">{{user_initials}}</div>
        {% endif %}
        <h2 class="mr-2 mb-0">{{title}}</h2>
        <a class="text-dark mr-2 mt-1 icon" href="{% url edit_link item_id %}"><i class="fas fa-pencil-alt"></i></a>
        {% if delete_status %}
          <a  class="mr-2 text-dark  mt-1 icon" href="{% url delete_link item_id %}"><i class="far fa-trash-alt"></i></a>
        {% else %}
          <i class="far fa-trash-alt mr-2 mt-1 icon text-muted" data-toggle="tooltip" data-placement="top" title="This item cannot be deleted"></i>
        {% endif %}
      </div>
    </div>
    <div class="col">
      {% if parent_item %}
        <a class="text-muted ticket-description" href="{% url parent_item_link parent_item_id %}">{{parent_item}}</a>
      {% endif %}
      <p>{{description}}</p>
    </div>
  </div>
  <div class="col">
    <h6>{{date_description}}: {{due_date|date:'l, F d, Y'}}</h6>
    <h6>{{status_description}}: {% status_badge status %}</h6>
    {% if sub_items %}
      {% if status != "Complete" and status != "Not Started" %}
        {% progress_bar progress.Total progress.Complete progress.Active %}
      {% endif %}
    {% endif %}
  </div>
</div>

check_mate/templates/reusable_components/status_badge.html
{% if status == "Active" %}
  <span class="badge badge-info">{{status}}</span>
{% elif status == "Road Block" %}
  <span class="badge badge-danger">{{status}}</span>
{% elif status == "Complete" %}
  <span class="badge badge-success">{{status}}</span>
{% else %}
  <span class="badge badge-light">{{status}}</span>
{% endif %}

check_mate/templates/reusable_components/task_card.html
{% load status_badge %}

{% if claim or claim_edit == True %}
<style>
  input:checked+label{
    border:2px solid #5bc0de;
  }
</style>
{% endif %}

{% if claim == True %}
  <input type="checkbox" class="d-none" id="claimed-task-{{task.id}}" name="task-{{task.id}}"/>
{% elif claim_edit == True %}
  <input type="checkbox" checked class="d-none" id="claimed-task-{{task.id}}" name="task-{{task.id}}"/>
{% endif %}

<!-- Card Wrapper -->
<label class="card mb-2" style="width: 16rem;" for="claimed-task-{{task.id}}">
  <!-- Card Body -->
  <div class="card-body">
    <div class="card-title text-dark">{{task.task_name}}</div>
    <p class="card-text ticket-description mb-2 text-muted">{{task.task_description}}</p>
    {% status_badge task.task_status%}

    {% if task.get_due_date_status == "This task is past due" %}
      <div class="card-text text-center text-danger ticket-description">{{task.get_due_date_status}}</div>
    {% elif task.get_due_date_status == "This task is due today" %}
      <div class="card-text text-center text-warning ticket-description">{{task.get_due_date_status}}</div>
    {% endif %}
  </div>
  <!-- End Card Body -->
  <!-- Card Footer -->
  <div class="card-footer bg-transparent">
    <div class="row">
      <div class="col">
        {% if user_initials %}
          <div class="text-white initials-circle bg-info">{{user_initials}}</div>
        {% endif %}
      </div>
      <div class="col text-right">
        <a class="text-dark" href="{% url 'check_mate:task_edit' task.id %}"><i class="fas fa-pencil-alt"></i></a>
        {% if task.delete_status == True %}
          <a class="text-dark" href="{% url 'check_mate:task_delete' task.id %}"><i class="far fa-trash-alt"></i></a>
        {% else %}
          <i class="far fa-trash-alt text-muted" data-toggle="tooltip" data-placement="top" title="You cannot delete active tasks"></i>
        {% endif %}
      </div>
    </div>
  </div>
  <!-- End Card Footer -->
  <!-- Card Tag Display -->
  {% if task.tags.all %}
  <div class="card-footer bg-transparent">
    <div class="row">
      <div class="col">
        {% for tag in task.tags.all %}
          <span class="badge badge-secondary">{{tag.tag_name}}</span>
        {% endfor %}
      </div>
    </div>
  </div>
  {% endif %}
  <!-- End Card Tag Display -->
</label>
<!-- End Card Wrapper -->

check_mate/templates/reusable_components/ticket_card.html
{% load progress_bar %}

{% if claim or claim_edit == True %}
<style>
  input:checked+label{
    border: 2px solid #5bc0de;
  }
</style>
{% endif %}

{% if claim == True %}
  <input type="checkbox" class="d-none" id="claimed-ticket-{{ticket.id}}" name="ticket-{{ticket.id}}"/>
{% elif claim_edit == True %}
  <input type="checkbox" checked class="d-none" id="claimed-ticket-{{ticket.id}}" name="ticket-{{ticket.id}}"/>
{% endif %}

<!-- Card Wrapper -->
<label class="card mb-2" style="width: 16rem;" for="claimed-ticket-{{ticket.id}}">
  <a href="{% url 'check_mate:ticket_details' ticket.id %}">
    <!-- Card Body -->
    <div class="card-body">
      <div class="card-title text-dark">{{ticket.ticket_name}}</div>
      <p class="card-text ticket-description mb-2 text-muted">{{ticket.ticket_description}}</p>
      {% progress_bar ticket.get_task_status.Total ticket.get_task_status.Complete ticket.get_task_status.Active %}
      {% if ticket.get_due_date_status == "This ticket is past due" %}
        <div class="card-text text-center text-danger ticket-description">{{ticket.get_due_date_status}}</div>
      {% elif ticket.get_due_date_status == "This ticket is due today" %}
        <div class="card-text text-center text-warning ticket-description">{{ticket.get_due_date_status}}</div>
      {% endif %}
    </div>
    <!-- End Card Body -->
  </a>
  <!-- Card Footer -->
  <div class="card-footer bg-transparent">
    <div class="row">
      <div class="col">
      {% if user_initials %}
        <div class="text-white initials-circle bg-info">{{user_initials}}</div>
      {% endif %}
      </div>
      <div class="col text-right mt-0">
        <a class="text-dark icon" href="{% url 'check_mate:ticket_edit' ticket.id %}"><i class="fas fa-pencil-alt"></i></a>
        {% if ticket.delete_status == True %}
          <a class="text-dark icon" href="{% url 'check_mate:ticket_delete' ticket.id %}"><i class="far fa-trash-alt"></i></a>
        {% else %}
          <i class="far fa-trash-alt text-muted icon" data-toggle="tooltip" data-placement="top" title="You cannot delete a ticket with active tasks"></i>
        {% endif %}
      </div>
    </div>
  </div>
  <!-- End Card Footer -->
  {% if ticket.tags.all %}
  <!-- Card Tag Display -->
  <div class="card-footer bg-transparent">
    <div class="row">
      <div class="col">
        {% for tag in ticket.tags.all %}
          <span class="badge badge-secondary">{{tag.tag_name}}</span>
        {% endfor %}
      </div>
    </div>
  </div>
  <!-- End Card Tag Display -->
  {% endif %}
</label>
<!-- End Card Body -->